"""add class_index and skill_proficiencies to characters

Revision ID: 9c7ebc00ac93
Revises: 2c5954a2250b
Create Date: 2026-09-06 18:36:05.478397

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c7ebc00ac93"
down_revision: str | Sequence[str] | None = "2c5954a2250b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("characters", sa.Column("class_index", sa.String(), nullable=True))
    # server_default needed here (unlike the model's plain Python-side
    # default=list) because SQLite can't add a NOT NULL column to a table
    # that already has rows without one - found live applying this exact
    # migration against the dev DB, which already had a character row.
    op.add_column(
        "characters",
        sa.Column("skill_proficiencies", sa.JSON(), nullable=False, server_default="[]"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("characters", "skill_proficiencies")
    op.drop_column("characters", "class_index")
    # ### end Alembic commands ###
