"""add prepared_spells to characters

Revision ID: a9c7ddc3736e
Revises: a7237fd2c628
Create Date: 2026-09-22 09:13:50.945580

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9c7ddc3736e"
down_revision: str | Sequence[str] | None = "a7237fd2c628"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "characters", sa.Column("prepared_spells", sa.JSON(), server_default="[]", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("characters", "prepared_spells")
    # ### end Alembic commands ###
