"""Builds docs/class-playtest/results.md from the raw
harness output, linking each failing play to the GitHub issue filed for it.

    uv run python scripts/class_playtest_report.py

Inputs (written by class_playtest.py): plays_all.json (first full run),
plays_rerun.json (second run after check fixes + added plays - wins where both
have a play), static.json, spell_sweep.json."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

OUT = Path(__file__).resolve().parent.parent / "docs" / "class-playtest"

# (class, play name) -> issues. Plays that pass are never looked up.
ISSUES: dict[tuple[str, str], list[int]] = {
    ("barbarian", "throw a javelin (not wielded)"): [83],
    ("barbarian", "attack, then rage"): [76],
    ("bard", "sleep on a pack"): [78],
    ("bard", "charm person"): [96],
    ("bard", "minor illusion (flavor cantrip)"): [55],
    ("bard", "vicious mockery"): [97],
    ("bard", "thunderwave"): [97],
    ("bard", "talk the goblin down"): [102],
    ("cleric", "cure wounds (Life domain)"): [88],
    ("cleric", "command"): [96],
    ("cleric", "heal self"): [99],
    ("cleric", "guidance"): [55],
    ("cleric", "guiding bolt"): [97],
    ("cleric", "attack, then healing word"): [76],
    ("druid", "produce flame"): [98],
    ("druid", "shillelagh"): [95],
    ("druid", "entangle"): [78, 96],
    ("druid", "goodberry"): [55],
    ("druid", "faerie fire"): [78, 96],
    ("druid", "attack, then healing word"): [76],
    ("fighter", "attack, then second wind"): [76],
    ("fighter", "shoved target gets back up"): [82],
    ("fighter", "common: ready an action"): [100],
    ("fighter", "common: break a grapple"): [100],
    ("fighter", "common: stand up from prone"): [82],
    ("monk", "punch"): [77],
    ("monk", "punch + bonus kick"): [76, 77],
    ("monk", "throw a dart"): [98],
    ("monk", "tumble"): [101],
    ("paladin", "lay on hands"): [86],
    ("paladin", "divine sense"): [87],
    ("ranger", "track"): [101],
    ("ranger", "hide"): [84],
    ("rogue", "shortbow"): [83],
    ("rogue", "hide"): [84],
    ("rogue", "expertise stealth"): [85],
    ("rogue", "sneak attack once per turn when dual-wielding"): [81],
    ("rogue", "pickpocket"): [101],
    ("sorcerer", "burning hands on a pack"): [78, 79],
    ("sorcerer", "fire bolt at point blank"): [80],
    ("sorcerer", "ray of frost"): [97],
    ("warlock", "charm person"): [96],
    ("warlock", "off-list spell is refused"): [91],
    ("wizard", "sleep a pack"): [78],
    ("wizard", "shield"): [93],
    ("wizard", "find familiar"): [56],
}

STATIC_ISSUES: dict[tuple[str, str], list[int]] = {
    ("fighter", "fighting style: great-weapon-fighting"): [92],
    ("fighter", "fighting style: protection"): [92],
    ("fighter", "fighting style: two-weapon-fighting"): [92],
    ("cleric", "Life domain heavy armor (chain mail)"): [88],
    ("sorcerer", "Draconic Resilience AC (13 + DEX 2 = 15)"): [89],
    ("sorcerer", "Draconic Resilience HP (+1)"): [89],
    ("warlock", "Pact Magic slots refresh on short rest"): [90],
    ("warlock", "has any spell list / known spells"): [91],
    ("paladin", "class resource: Lay on Hands pool"): [86],
    ("rogue", "Expertise is modeled on the character"): [85],
}

RERUN_CLASSES = {
    "barbarian",
    "cleric",
    "druid",
    "fighter",
    "monk",
    "paladin",
    "rogue",
    "sorcerer",
}


def links(nums: list[int]) -> str:
    return ", ".join(f"#{n}" for n in nums)


def merged_plays() -> list[dict[str, Any]]:
    first = json.loads((OUT / "plays_all.json").read_text(encoding="utf-8"))
    rerun = json.loads((OUT / "plays_rerun.json").read_text(encoding="utf-8"))
    latest = {(r["class"], r["play"]): r for r in first if r["class"] not in RERUN_CLASSES}
    latest.update({(r["class"], r["play"]): r for r in rerun})
    order = ["barbarian", "bard", "cleric", "druid", "fighter", "monk"]
    order += ["paladin", "ranger", "rogue", "sorcerer", "warlock", "wizard"]
    return sorted(latest.values(), key=lambda r: (order.index(r["class"]), r["play"]))


def verdict(r: dict[str, Any]) -> str:
    n, k = r["trials"], r["passed_trials"]
    return "pass" if k == n else ("flaky" if k else "FAIL")


def main() -> None:
    plays = merged_plays()
    lines = ["# Class playtest results", "", "Generated by `scripts/class_playtest_report.py`.", ""]

    total = len(plays)
    passed = sum(verdict(r) == "pass" for r in plays)
    lines += [
        f"**Plays:** {total} - {passed} pass, "
        f"{sum(verdict(r) == 'flaky' for r in plays)} flaky, "
        f"{sum(verdict(r) == 'FAIL' for r in plays)} fail (2 parse trials each; dice rigged).",
        "",
    ]

    lines += ["## Per-class plays", ""]
    current = ""
    for r in plays:
        if r["class"] != current:
            current = r["class"]
            lines += [
                "",
                f"### {current.title()}",
                "",
                "| Result | Play | What the player typed | Issue |",
                "|---|---|---|---|",
            ]
        v = verdict(r)
        icon = {"pass": "pass", "flaky": "flaky", "FAIL": "**FAIL**"}[v]
        issue = links(ISSUES.get((r["class"], r["play"]), [])) if v != "pass" else ""
        notes = [p for p in r["problems"] if p.startswith("NOTE:")]
        if v == "pass" and notes:
            icon = "pass (note)"
            issue = links(ISSUES.get((r["class"], r["play"]), []))
        lines.append(f"| {icon} | {r['play']} | {r['utterance']} | {issue} |")

    static = json.loads((OUT / "static.json").read_text(encoding="utf-8"))
    lines += [
        "",
        "## Creation-time checks",
        "",
        "| Result | Class | Check | Detail | Issue |",
        "|---|---|---|---|---|",
    ]
    for s in static:
        if s["check"].startswith(("class features list", "spell list")):
            continue
        issue = "" if s["ok"] else links(STATIC_ISSUES.get((s["class"], s["check"]), []))
        lines.append(
            f"| {'ok' if s['ok'] else '**FAIL**'} | {s['class']} | {s['check']} | "
            f"{str(s['detail'])[:90]} | {issue} |"
        )
    lines.append(
        "| **FAIL** | all | SRD level-1 class features listed on the character/sheet "
        "| none exposed | #103 |"
    )

    sweep = json.loads((OUT / "spell_sweep.json").read_text(encoding="utf-8"))
    lines += ["", "## Spell sweep (level 0-1 spells on each caster's list, cast for real)", ""]
    lines += ["| Class | castable | unsupported | errored |", "|---|---|---|---|"]
    for cls in ["bard", "cleric", "druid", "sorcerer", "warlock", "wizard"]:
        rows = [x for x in sweep if x["class"] == cls]
        ok = sum(x["status"] == "castable" for x in rows)
        bad = [x["spell"] for x in rows if x["status"] == "UNSUPPORTED"]
        err = [x["spell"] for x in rows if x["status"] == "error"]
        lines.append(f"| {cls} | {ok} | {len(bad)}: {', '.join(bad)} | {', '.join(err) or '-'} |")
    lines += [
        "",
        "'castable' only means the cast didn't error - save-or-effect spells that roll a save and "
        "apply nothing (#96) and spells whose rider is dropped (#97) are counted as castable.",
        "",
    ]
    (OUT / "results.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"{total} plays, {passed} pass; wrote {OUT / 'results.md'}")


if __name__ == "__main__":
    main()
